# Generated by Django 3.0.6 on 2020-07-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_data_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_set',
        ),
    ]
