# Generated by Django 3.0.6 on 2020-07-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0012_delete_data_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=255)),
                ('league_logo', models.ImageField(upload_to='league_logos')),
                ('league_address', models.CharField(max_length=255)),
                ('league_number', models.CharField(max_length=25)),
                ('league_more_info', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=255)),
                ('parent_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.league')),
            ],
        ),
    ]
