# Generated by Django 3.0.6 on 2020-07-22 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_division_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 2, 38, 3, 476556)),
        ),
        migrations.AddField(
            model_name='league',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 2, 38, 3, 475556)),
        ),
    ]
