# Generated by Django 3.0.6 on 2020-07-22 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20200722_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='league',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
