# Generated by Django 3.0.6 on 2020-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20200722_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
