# Generated by Django 3.0.6 on 2020-07-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20200722_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_pics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_img', models.ImageField(upload_to='profilePics')),
            ],
        ),
    ]
