# Generated by Django 3.0.6 on 2020-07-31 06:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0017_profile_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_logo', models.ImageField(upload_to='team_logos')),
                ('team_name', models.CharField(max_length=150)),
                ('representative_name', models.CharField(max_length=150)),
                ('representative_pic', models.ImageField(upload_to='representatives')),
                ('coach_name', models.CharField(max_length=150)),
                ('coach_pic', models.ImageField(upload_to='coaches')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('team_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
