# Generated by Django 3.0.6 on 2020-08-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_img', models.ImageField(upload_to='player_pics')),
                ('player_name', models.CharField(max_length=150)),
                ('player_phone', models.CharField(max_length=150)),
                ('player_dob', models.DateField()),
                ('parent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team')),
            ],
        ),
    ]
